### ISSUE TITLE
Pulmonary veins don’t clip

### ISSUE THREAD

**Issue by driainsim** [CemrgAppDevelopers/CemrgApp#12]
In some cases for the fire and ice study the veins do not clip - possibly related to the orientation of the file. Specific case folder has been shared with Jose

**Comment by alonsoJASL** [comment]
This issue is thought of being related to the orientation of the files. As part of fixing issue #13, we have included a module where the orientation is set to RAI in every image converted (regardless of the DICOM converter). Thus, I will close this issue, with the possibility if reopening it if the problem is not fully fixed.
