### ISSUE TITLE
Allow project directory paths with spaces and punctuation in the path

### ISSUE THREAD

**Issue by drsewilliams** [CemrgAppDevelopers/CemrgApp#25]
Many directories insist on having spaces = e.g. when Iain has shared files with me through OneDrive the obligatory have space such as "Sim, Iain - SegmentationFolders/..."

**Comment by drsewilliams** [comment]
Hi Jose, I would put this as higher than low priority, I think. It is a pretty big limitation to the work flow - e.g. on Mac; an external drive with a space in the name counts as a space in the path.

**Comment by OrodRazeghi** [comment]
OP's requested feature can cause issues with the underlying commandline interface and how different operating systems handle wild chars and escape the space character in the path. Due to the major changes that the requested feature requires to produce a bug free solution, the issue will be closed for now.
