### ISSUE TITLE
Add feature to allow 'trial' confirm of 3-Dimensional interpolation of segmentation

### ISSUE THREAD

**Issue by drsewilliams** [CemrgAppDevelopers/CemrgApp#27]
I think it would be useful to have a way to see what the segmentation is going to look like after applying the 3D segmentation; and have the option of not accepting if further editing is needed.

**Comment by OrodRazeghi** [comment]
The generated green contours present the segmented region of interest after the 3D interpolation operation, which can be used to evaluate the quality of the segmentation done manually. Also, the OP's requested feature to see the segmentation label already exists in the _segmentation view_.

By turning off the 3D interpolation option, in fact, the segmented slices can be edited again and once done, a new 3D interpolation can be applied to update the overall segmentation. However, this is only available if the _segmentation view_ has not been closed. The 3D interpolation method does not recognise previously saved/old segmentations, which is unfortunately at the moment a limitation of the MITK platform.

**Comment by drsewilliams** [comment]
Thanks Orod, I haven't really been accurate in the description. What I mean is to be able to see a trial of the _surface_ that would be created from the _segmentation_. I know that the green outline shows how the 3D segmentation will look. The surface is sometimes different though. I'm referring to regions e.g. where the veins are close to the body of the LA or the LUPV is close to the LAA.

**Comment by OrodRazeghi** [comment]
A temporary surface can be created by right clicking on the segmentation node in the data manager and choosing from "create polygon model" or "create smooth polygon model" from the context menu. If needed the segmentation process can be continued and this step can be repeated for better visualisation. The changes in the final surface that sometimes appear in the pipeline are due to the smoothing operations performed on the mesh by the MIRTK toolkit. The GUI box that pops up at the "create surface" step has two inputs for controlling the smoothness of the surface: "Blur" and "Smooth". Blur is applied to the segmentation image directly (usually not needed) and Smooth is performed on the mesh. By decreasing the Smooth value, you will get a closer mesh to the original segmentation.
