### ISSUE TITLE
Undefined symbols for architecture x86_64:   "___kmpc_end_reduce_nowait", referenced from:       _.omp_outlined._debug__.9 i

### ISSUE THREAD

**Issue by sverdlab** [CemrgAppDevelopers/CemrgApp#71]
Hi could you please help me - I got this compilation error (on Mac OSx - Catalina):

[ 16%] Built target MitkAnnotation
[ 16%] Built target MitkLegacyGL
[ 16%] Linking CXX shared library ../../lib/libMitkAlgorithmsExt.dylib
Undefined symbols for architecture x86_64:
  "___kmpc_end_reduce_nowait", referenced from:
      _.omp_outlined._debug__.9 in mitkWeightedPointTransform.cpp.o
  "___kmpc_for_static_fini", referenced from:
      _.omp_outlined._debug__ in mitkAnisotropicIterativeClosestPointRegistration.cpp.o
      _.omp_outlined._debug__ in mitkWeightedPointTransform.cpp.o
      _.omp_outlined._debug__.1 in mitkWeightedPointTransform.cpp.o]

Thank you!

**Comment by alonsoJASL** [comment]
Hello @sverdlab, 

First, I would like to encourage you to stick to our [Reporting Bugs Guidelines](https://github.com/OpenHeartDevelopers/CemrgApp/wiki/Reporting-bugs) and using the [ISSUE TEMPLATE](https://github.com/OpenHeartDevelopers/CemrgApp/wiki/ISSUE_TEMPLATE.md). It can be very difficult to help you by relying solely on terminal outputs like the one you're sharing. 

Secondly, **from your error log**, I can gather three thoughts: 
+ The architecture you are building is not supported. this could be because you are using an ARM chip instead of an INTEL one; although that is not consistent with you stating that you are building the app in Catalina. 
+ I am not sure that we build the `mitkWeightedPointTransform` class, which suggests to check your cmake configuration.
+ I see `debug` in your log, I don't know if this is relevant, but make sure you are setting the `CMAKE_BUILD_TYPE` variable to `Release`.
> Once again, since I only have your log to go from, it is hard to be more helpful.  Consider using the [ISSUE TEMPLATE](https://github.com/OpenHeartDevelopers/CemrgApp/wiki/ISSUE_TEMPLATE.md)

Finally, it would be useful to know why do you want to build the application so that we can give you better guidance. We do have some [releases](https://github.com/OpenHeartDevelopers/CemrgApp/releases/tag/v2.2) available in all major platforms.

**Comment by alonsoJASL** [comment]
Closing, will re-open based on OP's response.
